openapi: 3.1.0
security:
  - APIKey: []
info:
  title: Ding
  version: 1.0.0
  description: "The OTP API allows you to send authentication codes to your users using their phone numbers."
servers:
  - url: "https://api.ding.live/v1"
    description: The production Ding API server
tags:
  - name: OTP
    description: Send OTP codes to your users using their phone numbers.
  - name: Lookup
    description: Retrieve up-to-date metadata about a specific phone number
paths:
  /authentication:
    post:
      x-speakeasy-usage-example:
        title: Send a code
        description: |
          Send an OTP code to a user's phone number.
        position: 1
      summary: Send a code
      tags:
        - OTP
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAuthenticationResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: create-authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAuthenticationRequest"
  /check:
    post:
      x-speakeasy-usage-example:
        title: Check a code
        description: |
          Check that a code entered by a user is valid.
        position: 2
      summary: Check a code
      tags:
        - OTP
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateCheckResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: check
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCheckRequest"
  /authentication/feedback:
    post:
      summary: Send feedback
      tags:
        - OTP
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedbackResponse"
        default:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: feedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackRequest"
  /retry:
    post:
      x-speakeasy-usage-example:
        title: Perform a retry
        description: |
          Perform a retry if a user has not received the code.
        position: 3
      summary: Perform a retry
      tags:
        - OTP
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetryAuthenticationResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: retry
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RetryAuthenticationRequest"
  /lookup/{phone_number}:
    get:
      summary: Perform a phone number lookup
      tags:
        - Lookup
      parameters:
        - in: header
          name: customer-uuid
          schema:
            type: string
            format: uuid
            description: Your customer UUID, which can be found in the API settings in the dashboard.
          required: true
        - in: path
          name: phone_number
          required: true
          schema:
            type: string
            format: phone_number
            description: An E.164 formatted phone number to look up.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LookupResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: lookup
components:
  schemas:
    FeedbackRequest:
      type: object
      required:
        - customer_uuid
        - phone_number
        - status
      properties:
        customer_uuid:
          type: string
          format: uuid
          description: Your customer UUID, which can be found in the API settings in the dashboard.
        phone_number:
          type: string
          format: phone_number
          examples: ["+1234567890"]
          description: An E.164 formatted phone number.
        status:
          type: string
          examples: ["onboarded"]
          description: The type of the feedback.
          enum:
            - onboarded
    FeedbackResponse:
      type: object
      properties:
        uuid:
          type: string
          examples: ["123e4567-e89b-12d3-a456-4266141740a0"]
          description: The UUID of the feedback.
    LookupResponse:
      type: object
      properties:
        phone_number:
          type: string
          format: phone_number
          examples: ["+1234567890"]
          description: An E.164 formatted phone number.
        mcc:
          type: string
          examples: ["310"]
          description: The mobile country code of the phone number.
        mnc:
          type: string
          examples: ["410"]
          description: The mobile network code of the phone number.
        carrier:
          type: string
          examples: ["AT&T"]
          description: The carrier of the phone number.
        country_code:
          type: string
          examples: ["US"]
          description: The ISO 3166-1 alpha-2 country code of the phone number.
        number_ported:
          type: boolean
          description: Whether the phone number has been ported.
        line_type:
          type: string
          examples: ["Mobile"]
          description: The type of phone line.
          enum:
            - FixedLine
            - Mobile
            - TollFree
            - PremiumRate
            - SharedCost
            - Voip
            - Pager
            - VoiceMail
            - UniversalAccess
            - Service
            - Unknown
    RetryAuthenticationResponse:
      type: object
      properties:
        authentication_uuid:
          type: string
          format: uuid
          description: The UUID of the corresponding authentication.
        status:
          type: string
          description: >
            The status of the retry. Possible values are:
              * `approved` - The retry was approved and a new code was sent.
              * `denied` - The retry was denied.
              * `no_attempt` - No attempt was sent yet, so a retry cannot be completed.
              * `rate_limited` - The authentication was rate limited and cannot be retried.
              * `expired_auth` - The authentication has expired and cannot be retried.
              * `already_validated` - The authentication has already been validated.
          examples: ["approved"]
          enum:
            - approved
            - denied
            - no_attempt
            - rate_limited
            - expired_auth
            - already_validated
        created_at:
          type: string
          format: date-time
        next_retry_at:
          type: string
          format: date-time
          description: The time at which the next retry will be available.
        remaining_retry:
          type: integer
          minimum: 0
          examples: [3]
          description: The number of remaining retries.
    RetryAuthenticationRequest:
      type: object
      required:
        - customer_uuid
        - authentication_uuid
      properties:
        customer_uuid:
          type: string
          format: uuid
          description: Your customer UUID, which can be found in the API settings in the dashboard.
        authentication_uuid:
          type: string
          format: uuid
          description: The authentication UUID that was returned when you created the authentication.
    CreateCheckResponse:
      type: object
      properties:
        authentication_uuid:
          type: string
          format: uuid
          description: The UUID of the corresponding authentication.
        status:
          type: string
          examples: ["valid"]
          description: >
            The status of the check. Possible values are:
              * `valid` - The code is valid.
              * `invalid` - The code is invalid.
              * `without_attempt` - No attempt was sent yet, so a check cannot be completed.
              * `rate_limited` - The authentication was rate limited and cannot be checked.
              * `already_validated` - The authentication has already been validated.
              * `expired_auth` - The authentication has expired and cannot be checked.
          enum:
            - valid
            - invalid
            - without_attempt
            - rate_limited
            - already_validated
            - expired_auth
    CreateCheckRequest:
      type: object
      required:
        - customer_uuid
        - authentication_uuid
        - check_code
      properties:
        customer_uuid:
          type: string
          format: uuid
          description: Your customer UUID, which can be found in the API settings in the Dashboard.
        authentication_uuid:
          type: string
          format: uuid
          description: The authentication UUID that was returned when you created the authentication.
        check_code:
          type: string
          examples: ["123456"]
          description: The code that the user entered.
    CreateAuthenticationRequest:
      type: object
      required:
        - customer_uuid
        - phone_number
      properties:
        customer_uuid:
          type: string
          format: uuid
          description: Your customer UUID, which can be found in the API settings in the dashboard.
        phone_number:
          type: string
          format: phone_number
          examples: ["+1234567890"]
          description: An E.164 formatted phone number to send the OTP to.
        ip:
          type: string
          format: ipv4
          description: The IP address of the user's device.
        device_id:
          type: string
          description: Unique identifier for the user's device. For Android, this corresponds to the `ANDROID_ID` and for iOS, this corresponds to the `identifierForVendor`.
        device_type:
          type: string
          enum:
            - IOS
            - ANDROID
            - WEB
          description: The type of device the user is using.
        app_version:
          type: string
          description: The version of your application.
        callback_url:
          type: string
          format: url
          description: A webhook URL to which delivery statuses will be sent.
        app_realm:
          type: string
          description:
            The Android SMS Retriever API hash code that identifies your app.
            This allows you to automatically retrieve and fill the OTP code on Android devices.
        os_version:
          type: string
          description: The version of the user's device operating system.
        device_model:
          type: string
          description: The model of the user's device.
        is_returning_user:
          type: boolean
          description: Whether the user is a returning user on your app.
        template_id:
          type: string
          description: The template id associated with the message content variant to be sent.
    CreateAuthenticationResponse:
      type: object
      description: A successful response to an authentication creation request.
      properties:
        authentication_uuid:
          type: string
          format: uuid
          description: A unique identifier for the authentication that you can use on the /check and /retry endpoints.
        status:
          type: string
          description: >
            The status of the authentication. Possible values are:
              * `pending` - The OTP code is being sent.
              * `rate_limited` - This user is rate-limited and cannot receive another code.
              * `spam_detected` - This attempt is flagged as spam. Go to the dashboard for more details.
          enum:
            - pending
            - rate_limited
            - spam_detected
        created_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
          description: The time at which the authentication expires and can no longer be checked or retried.
    # -------------------------------------------------------------------------
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          examples: ["invalid_phone_number"]
          description: >
            A machine-readable code that describes the error. Possible values are:
              * `invalid_phone_number` - This is not a valid E.164 number.
              * `internal_server_error` - An internal server error occurred.
              * `bad_request` - The request was malformed.
              * `account_invalid` - The provided customer UUID is invalid.
              * `negative_balance` - You have a negative balance.
              * `invalid_line` - Ding does not support this type of phone number.
              * `unsupported_region` - Ding does not support this region yet.
              * `invalid_auth_uuid` - The provided authentication UUID is invalid.
              * `blocked_number` - The phone number is in the blocklist.
              * `invalid_app_version` - The provided application version is invalid.
              * `invalid_os_version` - The provided OS version is invalid.
              * `invalid_device_model` - The provided device model is invalid.
              * `invalid_device_id` - The provided device ID is invalid.
              * `no_associated_auth_found` - The associated authentication was not found.
              * `duplicated_feedback_status` - Duplicated feedback status has found.
              * `invalid_feedback_status` - The provided feedback status is invalid.
              * `invalid_template_id` - The provided template ID is invalid.
          enum:
            - invalid_phone_number
            - internal_server_error
            - bad_request
            - account_invalid
            - negative_balance
            - invalid_line
            - unsupported_region
            - invalid_auth_uuid
            - invalid_app_realm
            - unsupported_app_realm_device_type
            - app_realm_require_device_type
            - blocked_number
            - invalid_app_version
            - invalid_os_version
            - invalid_device_model
            - invalid_device_id
            - no_associated_auth_found
            - duplicated_feedback_status
            - invalid_feedback_status
            - invalid_template_id
        message:
          type: string
          examples: ["+0 is not a valid phone number"]
          description: A human-readable message that describes the error.
        doc_url:
          type: string
          description: A link to the documentation that describes the error.
          examples:
            ["https://docs.ding.live/api-reference/errors#invalid_phone_number"]
  securitySchemes:
    APIKey:
      name: x-api-key
      type: apiKey
      in: header
      x-speakeasy-example: YOUR_API_KEY
